#!/bin/bash

# allow running from anywhere when
# making an alias in .bashrc or /etc/environment: vpn="path/to/./run"

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$(dirname "$(realpath "$0")")";
echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"

# place to save config files: $HOME/.config/vpngate-with-proxy
user_home=($HOME)
control=$1
arg=$2

# assign the right python version here
PY=python3.6

# __________check setup__________
sudo $PY setup.py $user_home || exit 1

# __________ parse argv __________
if [ "$control" == "stop" ]; then
   sudo kill `pgrep -f "vpn_manager.py"`    # don't worry, the manager will cleanup before exiting
   exit
fi

if [ "$control" == "log" ]; then
   ls=`dir logs`
   tail -f "logs/${ls: -16}"
   exit
fi

if [ "$control" == "restart" ]; then
   sudo kill `pgrep -f "vpn_manager.py"`    # don't worry, the manager will cleanup before exiting
fi

# __________check if server is running__________
res=`pgrep -af "vpn_manager.py"`

if [ "$control" == "status" ]; then
   [[ ! -z  $res  ]] && echo "vpn_manager is running: $res" && exit
   echo "vpn_manager is stopped" && exit
fi

# __________launch server if not exist__________
if [ -z "$res" ]; then
    sudo $PY -u vpn_manager.py $user_home
fi

# __________launch UI client__________
sleep 0.2
$PY UI.py $user_home